import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/Navigation";

const primaryFont = Public_Sans({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-public-sans",
  fallback: ["Helvetica", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${primaryFont.variable} font-sans antialiased min-h-screen h-full`}>
        <div className="relative min-h-screen bg-stone-50">
          <div className="bg-sky-400 w-full sm:w-40 h-40 rounded-full absolute top-1 opacity-20 max-sm:right-0 sm:left-56 z-0" />
          <div className="bg-emerald-500 w-full sm:w-40 h-24 absolute top-0 -left-0 opacity-20 z-0" />
          <div className="bg-purple-600 w-full sm:w-40 h-24 absolute top-40 -left-0 opacity-20 z-0" />

          <div className="min-h-screen flex flex-col relative z-10 backdrop-blur-3xl">
            <div className="w-full max-w-w-max mx-auto px-2 lg:px-8 pt-12">
              <Navigation />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
